export type RepresentativeType = "House" | "Senate";

export type Representative = {
  name: string;
  alignment: "Republican";
  type: RepresentativeType;
  location: string;
  state_xx: string;
  seat: string | null;
  seat_number: number | null;
  state_name: string;
  election_year: number;
  win_margin: number;
  image: string;
  act_blue_url: string;
};

export default class Data {
  public static readonly ALL_STATES = [
    "AL",
    "AK",
    "AZ",
    "AR",
    "CA",
    "CO",
    "CT",
    "DE",
    "DC",
    "FL",
    "GA",
    "GU",
    "HI",
    "ID",
    "IL",
    "IN",
    "IA",
    "KS",
    "KY",
    "LA",
    "ME",
    "MD",
    "MA",
    "MI",
    "MN",
    "MS",
    "MO",
    "MT",
    "NE",
    "NV",
    "NH",
    "NJ",
    "NM",
    "NY",
    "NC",
    "ND",
    "OH",
    "OK",
    "OR",
    "PA",
    "PR",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VT",
    "VA",
    "VI",
    "WA",
    "WV",
    "WI",
    "WY",
  ];
  public static readonly MEMBERS_OF_CONGRESS: Representative[] = [
    {
      name: "Robert B. Aderholt",
      alignment: "Republican",
      type: "House",
      location: "Ala.",
      state_xx: "AL",
      seat_number: 4,
      state_name: "Alabama",
      seat: "AL-04",
      election_year: 2022,
      win_margin: 0.64,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/aderholt-17-1-h.png",
      act_blue_url: "https://secure.actblue.com/directory/AL/all/fed-house",
    },
    {
      name: "Mo Brooks",
      alignment: "Republican",
      type: "House",
      location: "Ala.",
      state_xx: "AL",
      seat_number: 5,
      state_name: "Alabama",
      seat: "AL-05",
      election_year: 2022,
      win_margin: 1,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/brooks-60629-1-h.png",
      act_blue_url: "https://secure.actblue.com/directory/AL/all/fed-house",
    },
    {
      name: "Jerry Carl",
      alignment: "Republican",
      type: "House",
      location: "Ala.",
      state_xx: "AL",
      seat_number: 1,
      state_name: "Alabama",
      seat: "AL-01",
      election_year: 2022,
      win_margin: 0.28,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/carl-20073861-1-h.png",
      act_blue_url: "https://secure.actblue.com/directory/AL/all/fed-house",
    },
    {
      name: "Barry Moore",
      alignment: "Republican",
      type: "House",
      location: "Ala.",
      state_xx: "AL",
      seat_number: 2,
      state_name: "Alabama",
      seat: "AL-02",
      election_year: 2022,
      win_margin: 0.3,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/moore-20073840-1-h.png",
      act_blue_url: "https://secure.actblue.com/directory/AL/all/fed-house",
    },
    {
      name: "Gary Palmer",
      alignment: "Republican",
      type: "House",
      location: "Ala.",
      state_xx: "AL",
      seat_number: 6,
      state_name: "Alabama",
      seat: "AL-06",
      election_year: 2022,
      win_margin: 1,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/palmer-63532-1-h.png",
      act_blue_url: "https://secure.actblue.com/directory/AL/all/fed-house",
    },
    {
      name: "Mike Rogers",
      alignment: "Republican",
      type: "House",
      location: "Ala.",
      state_xx: "AL",
      seat_number: 3,
      state_name: "Alabama",
      seat: "AL-03",
      election_year: 2022,
      win_margin: 0.36,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/rogers-1161-1-h.png",
      act_blue_url: "https://secure.actblue.com/directory/AL/all/fed-house",
    },
    {
      name: "Tommy Tuberville",
      alignment: "Republican",
      type: "Senate",
      location: "Ala.",
      state_xx: "AL",
      seat_number: null,
      state_name: "Alabama",
      seat: null,
      election_year: 2026,
      win_margin: 0.2,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/tuberville-68308.png",
      act_blue_url: "https://secure.actblue.com/directory/AL/all/fed-senate",
    },
    {
      name: "Andy Biggs",
      alignment: "Republican",
      type: "House",
      location: "Ariz.",
      state_xx: "AZ",
      seat_number: 5,
      state_name: "Arizona",
      seat: "AZ-05",
      election_year: 2022,
      win_margin: 0.18,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/biggs-52611-3-h.png",
      act_blue_url: "https://secure.actblue.com/directory/AZ/all/fed-house",
    },
    {
      name: "Paul Gosar",
      alignment: "Republican",
      type: "House",
      location: "Ariz.",
      state_xx: "AZ",
      seat_number: 4,
      state_name: "Arizona",
      seat: "AZ-04",
      election_year: 2022,
      win_margin: 0.4,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/gosar-61424-3-h.png",
      act_blue_url: "https://secure.actblue.com/directory/AZ/all/fed-house",
    },
    {
      name: "Debbie Lesko",
      alignment: "Republican",
      type: "House",
      location: "Ariz.",
      state_xx: "AZ",
      seat_number: 8,
      state_name: "Arizona",
      seat: "AZ-08",
      election_year: 2022,
      win_margin: 0.2,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/lesko-19683-3-h.png",
      act_blue_url: "https://secure.actblue.com/directory/AZ/all/fed-house",
    },
    {
      name: "David Schweikert",
      alignment: "Republican",
      type: "House",
      location: "Ariz.",
      state_xx: "AZ",
      seat_number: 6,
      state_name: "Arizona",
      seat: "AZ-06",
      election_year: 2022,
      win_margin: 0.04,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/schweikert-5397-3-h.png",
      act_blue_url: "https://secure.actblue.com/directory/AZ/all/fed-house",
    },
    {
      name: "Rick Crawford",
      alignment: "Republican",
      type: "House",
      location: "Ark.",
      state_xx: "AR",
      seat_number: 1,
      state_name: "Arkansas",
      seat: "AR-01",
      election_year: 2022,
      win_margin: 1,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/crawford-60226-4-h.png",
      act_blue_url: "https://secure.actblue.com/directory/AR/all/fed-house",
    },
    {
      name: "Ken Calvert",
      alignment: "Republican",
      type: "House",
      location: "Calif.",
      state_xx: "CA",
      seat_number: 42,
      state_name: "California",
      seat: "CA-42",
      election_year: 2022,
      win_margin: 0.14,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/calvert-132-5-h.png",
      act_blue_url: "https://secure.actblue.com/directory/CA/all/fed-house",
    },
    {
      name: "Mike Garcia",
      alignment: "Republican",
      type: "House",
      location: "Calif.",
      state_xx: "CA",
      seat_number: 25,
      state_name: "California",
      seat: "CA-25",
      election_year: 2022,
      win_margin: 0,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/garcia-20073116-5-h.png",
      act_blue_url: "https://secure.actblue.com/directory/CA/all/fed-house",
    },
    {
      name: "Darrell Issa",
      alignment: "Republican",
      type: "House",
      location: "Calif.",
      state_xx: "CA",
      seat_number: 50,
      state_name: "California",
      seat: "CA-50",
      election_year: 2022,
      win_margin: 0.08,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/issa-146-5-h.png",
      act_blue_url: "https://secure.actblue.com/directory/CA/all/fed-house",
    },
    {
      name: "Doug LaMalfa",
      alignment: "Republican",
      type: "House",
      location: "Calif.",
      state_xx: "CA",
      seat_number: 1,
      state_name: "California",
      seat: "CA-01",
      election_year: 2022,
      win_margin: 0.14,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/lamalfa-52531-5-h.png",
      act_blue_url: "https://secure.actblue.com/directory/CA/all/fed-house",
    },
    {
      name: "Kevin McCarthy",
      alignment: "Republican",
      type: "House",
      location: "Calif.",
      state_xx: "CA",
      seat_number: 23,
      state_name: "California",
      seat: "CA-23",
      election_year: 2022,
      win_margin: 0.24,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/mccarthy-52561-5-h.png",
      act_blue_url: "https://secure.actblue.com/directory/CA/all/fed-house",
    },
    {
      name: "Devin Nunes",
      alignment: "Republican",
      type: "House",
      location: "Calif.",
      state_xx: "CA",
      seat_number: 22,
      state_name: "California",
      seat: "CA-22",
      election_year: 2022,
      win_margin: 0.08,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/nunes-67.png",
      act_blue_url: "https://secure.actblue.com/directory/CA/all/fed-house",
    },
    {
      name: "Jay Obernolte",
      alignment: "Republican",
      type: "House",
      location: "Calif.",
      state_xx: "CA",
      seat_number: 8,
      state_name: "California",
      seat: "CA-08",
      election_year: 2022,
      win_margin: 0.12,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/obernolte-20073428-5-h.png",
      act_blue_url: "https://secure.actblue.com/directory/CA/all/fed-house",
    },
    {
      name: "Lauren Boebert",
      alignment: "Republican",
      type: "House",
      location: "Colo.",
      state_xx: "CO",
      seat_number: 3,
      state_name: "Colorado",
      seat: "CO-03",
      election_year: 2022,
      win_margin: 0.06,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/boebert-20073825-6-h.png",
      act_blue_url: "https://secure.actblue.com/directory/CO/all/fed-house",
    },
    {
      name: "Doug Lamborn",
      alignment: "Republican",
      type: "House",
      location: "Colo.",
      state_xx: "CO",
      seat_number: 5,
      state_name: "Colorado",
      seat: "CO-05",
      election_year: 2022,
      win_margin: 0.21,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/lamborn-9174-6-h.png",
      act_blue_url: "https://secure.actblue.com/directory/CO/all/fed-house",
    },
    {
      name: "Kat Cammack",
      alignment: "Republican",
      type: "House",
      location: "Fla.",
      state_xx: "FL",
      seat_number: 3,
      state_name: "Florida",
      seat: "FL-03",
      election_year: 2022,
      win_margin: 0.14,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/cammack-20074006-10-h.png",
      act_blue_url: "https://secure.actblue.com/directory/FL/all/fed-house",
    },
    {
      name: "Mario Diaz-Balart",
      alignment: "Republican",
      type: "House",
      location: "Fla.",
      state_xx: "FL",
      seat_number: 25,
      state_name: "Florida",
      seat: "FL-25",
      election_year: 2022,
      win_margin: 1,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/diaz-balart-878.png",
      act_blue_url: "https://secure.actblue.com/directory/FL/all/fed-house",
    },
    {
      name: "Byron Donalds",
      alignment: "Republican",
      type: "House",
      location: "Fla.",
      state_xx: "FL",
      seat_number: 19,
      state_name: "Florida",
      seat: "FL-19",
      election_year: 2022,
      win_margin: 0.22,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/donalds-20061233-10-h.png",
      act_blue_url: "https://secure.actblue.com/directory/FL/all/fed-house",
    },
    {
      name: "Neal Dunn",
      alignment: "Republican",
      type: "House",
      location: "Fla.",
      state_xx: "FL",
      seat_number: 2,
      state_name: "Florida",
      seat: "FL-02",
      election_year: 2022,
      win_margin: 1,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/dunn-65654-10-h.png",
      act_blue_url: "https://secure.actblue.com/directory/FL/all/fed-house",
    },
    {
      name: "Scott Franklin",
      alignment: "Republican",
      type: "House",
      location: "Fla.",
      state_xx: "FL",
      seat_number: 15,
      state_name: "Florida",
      seat: "FL-15",
      election_year: 2022,
      win_margin: 0.1,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/franklin-69374.png",
      act_blue_url: "https://secure.actblue.com/directory/FL/all/fed-house",
    },
    {
      name: "Matt Gaetz",
      alignment: "Republican",
      type: "House",
      location: "Fla.",
      state_xx: "FL",
      seat_number: 1,
      state_name: "Florida",
      seat: "FL-01",
      election_year: 2022,
      win_margin: 0.31,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/gaetz-65653-10-h.png",
      act_blue_url: "https://secure.actblue.com/directory/FL/all/fed-house",
    },
    {
      name: "Carlos Gimenez",
      alignment: "Republican",
      type: "House",
      location: "Fla.",
      state_xx: "FL",
      seat_number: 26,
      state_name: "Florida",
      seat: "FL-26",
      election_year: 2022,
      win_margin: 0.04,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/gimenez-69391.png",
      act_blue_url: "https://secure.actblue.com/directory/FL/all/fed-house",
    },
    {
      name: "Brian Mast",
      alignment: "Republican",
      type: "House",
      location: "Fla.",
      state_xx: "FL",
      seat_number: 18,
      state_name: "Florida",
      seat: "FL-18",
      election_year: 2022,
      win_margin: 0.14,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/mast-65757-10-h.png",
      act_blue_url: "https://secure.actblue.com/directory/FL/all/fed-house",
    },
    {
      name: "Bill Posey",
      alignment: "Republican",
      type: "House",
      location: "Fla.",
      state_xx: "FL",
      seat_number: 8,
      state_name: "Florida",
      seat: "FL-08",
      election_year: 2022,
      win_margin: 0.22,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/posey-53077-10-h.png",
      act_blue_url: "https://secure.actblue.com/directory/FL/all/fed-house",
    },
    {
      name: "John Rutherford",
      alignment: "Republican",
      type: "House",
      location: "Fla.",
      state_xx: "FL",
      seat_number: 4,
      state_name: "Florida",
      seat: "FL-04",
      election_year: 2022,
      win_margin: 0.22,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/rutherford-65658-10-h.png",
      act_blue_url: "https://secure.actblue.com/directory/FL/all/fed-house",
    },
    {
      name: "Greg Steube",
      alignment: "Republican",
      type: "House",
      location: "Fla.",
      state_xx: "FL",
      seat_number: 17,
      state_name: "Florida",
      seat: "FL-17",
      election_year: 2022,
      win_margin: 0.31,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/steube-21084-10-h.png",
      act_blue_url: "https://secure.actblue.com/directory/FL/all/fed-house",
    },
    {
      name: "Daniel Webster",
      alignment: "Republican",
      type: "House",
      location: "Fla.",
      state_xx: "FL",
      seat_number: 11,
      state_name: "Florida",
      seat: "FL-11",
      election_year: 2022,
      win_margin: 0.34,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/webster-53062-10-h.png",
      act_blue_url: "https://secure.actblue.com/directory/FL/all/fed-house",
    },
    {
      name: "Rick Scott",
      alignment: "Republican",
      type: "Senate",
      location: "Fla.",
      state_xx: "FL",
      seat_number: null,
      state_name: "Florida",
      seat: null,
      election_year: 2024,
      win_margin: 0,
      image:
        "https://www.nytimes.com/newsgraphics/2018/congress-headshots/cutouts/scott-fl-sen.png",
      act_blue_url: "https://secure.actblue.com/directory/FL/all/fed-senate",
    },
    {
      name: "Rick Allen",
      alignment: "Republican",
      type: "House",
      location: "Ga.",
      state_xx: "GA",
      seat_number: 12,
      state_name: "Georgia",
      seat: "GA-12",
      election_year: 2022,
      win_margin: 0.16,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/allen-61316-11-h.png",
      act_blue_url: "https://secure.actblue.com/directory/GA/all/fed-house",
    },
    {
      name: 'Earl L. "Buddy" Carter',
      alignment: "Republican",
      type: "House",
      location: "Ga.",
      state_xx: "GA",
      seat_number: 1,
      state_name: "Georgia",
      seat: "GA-01",
      election_year: 2022,
      win_margin: 0.16,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/carter-63354-11-h.png",
      act_blue_url: "https://secure.actblue.com/directory/GA/all/fed-house",
    },
    {
      name: "Andrew Clyde",
      alignment: "Republican",
      type: "House",
      location: "Ga.",
      state_xx: "GA",
      seat_number: 9,
      state_name: "Georgia",
      seat: "GA-09",
      election_year: 2022,
      win_margin: 0.58,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/clyde-20073991-11-h.png",
      act_blue_url: "https://secure.actblue.com/directory/GA/all/fed-house",
    },
    {
      name: "Marjorie Taylor Greene",
      alignment: "Republican",
      type: "House",
      location: "Ga.",
      state_xx: "GA",
      seat_number: 14,
      state_name: "Georgia",
      seat: "GA-14",
      election_year: 2022,
      win_margin: 0.49,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/greene-20073466-11-h.png",
      act_blue_url: "https://secure.actblue.com/directory/GA/all/fed-house",
    },
    {
      name: "Jody Hice",
      alignment: "Republican",
      type: "House",
      location: "Ga.",
      state_xx: "GA",
      seat_number: 10,
      state_name: "Georgia",
      seat: "GA-10",
      election_year: 2022,
      win_margin: 0.24,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/hice-61020-11-h.png",
      act_blue_url: "https://secure.actblue.com/directory/GA/all/fed-house",
    },
    {
      name: "Barry Loudermilk",
      alignment: "Republican",
      type: "House",
      location: "Ga.",
      state_xx: "GA",
      seat_number: 11,
      state_name: "Georgia",
      seat: "GA-11",
      election_year: 2022,
      win_margin: 0.2,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/loudermilk-63369-11-h.png",
      act_blue_url: "https://secure.actblue.com/directory/GA/all/fed-house",
    },
    {
      name: "Russ Fulcher",
      alignment: "Republican",
      type: "House",
      location: "Idaho",
      state_xx: "ID",
      seat_number: 1,
      state_name: "Idaho",
      seat: "ID-01",
      election_year: 2022,
      win_margin: 0.39,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/fulcher-63500-13-h.png",
      act_blue_url: "https://secure.actblue.com/directory/ID/all/fed-house",
    },
    {
      name: "Mike Bost",
      alignment: "Republican",
      type: "House",
      location: "Ill.",
      state_xx: "IL",
      seat_number: 12,
      state_name: "Illinois",
      seat: "IL-12",
      election_year: 2022,
      win_margin: 0.2,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/bost-710-14-h.png",
      act_blue_url: "https://secure.actblue.com/directory/IL/all/fed-house",
    },
    {
      name: "Mary Miller",
      alignment: "Republican",
      type: "House",
      location: "Ill.",
      state_xx: "IL",
      seat_number: 15,
      state_name: "Illinois",
      seat: "IL-15",
      election_year: 2022,
      win_margin: 0.46,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/miller-68410.png",
      act_blue_url: "https://secure.actblue.com/directory/IL/all/fed-house",
    },
    {
      name: "Jim Baird",
      alignment: "Republican",
      type: "House",
      location: "Ind.",
      state_xx: "IN",
      seat_number: 4,
      state_name: "Indiana",
      seat: "IN-04",
      election_year: 2022,
      win_margin: 0.34,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/baird-19591-15-h.png",
      act_blue_url: "https://secure.actblue.com/directory/IN/all/fed-house",
    },
    {
      name: "Jim Banks",
      alignment: "Republican",
      type: "House",
      location: "Ind.",
      state_xx: "IN",
      seat_number: 3,
      state_name: "Indiana",
      seat: "IN-03",
      election_year: 2022,
      win_margin: 0.36,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/banks-64756-15-h.png",
      act_blue_url: "https://secure.actblue.com/directory/IN/all/fed-house",
    },
    {
      name: "Greg Pence",
      alignment: "Republican",
      type: "House",
      location: "Ind.",
      state_xx: "IN",
      seat_number: 6,
      state_name: "Indiana",
      seat: "IN-06",
      election_year: 2022,
      win_margin: 0.41,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/pence-19600-15-h.png",
      act_blue_url: "https://secure.actblue.com/directory/IN/all/fed-house",
    },
    {
      name: "Jackie Walorski",
      alignment: "Republican",
      type: "House",
      location: "Ind.",
      state_xx: "IN",
      seat_number: 2,
      state_name: "Indiana",
      seat: "IN-02",
      election_year: 2022,
      win_margin: 0.22,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/walorski-60423-15-h.png",
      act_blue_url: "https://secure.actblue.com/directory/IN/all/fed-house",
    },
    {
      name: "Ron Estes",
      alignment: "Republican",
      type: "House",
      location: "Kan.",
      state_xx: "KS",
      seat_number: 4,
      state_name: "Kansas",
      seat: "KS-04",
      election_year: 2022,
      win_margin: 0.28,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/estes-20240-17-h.png",
      act_blue_url: "https://secure.actblue.com/directory/KS/all/fed-house",
    },
    {
      name: "Jacob LaTurner",
      alignment: "Republican",
      type: "House",
      location: "Kan.",
      state_xx: "KS",
      seat_number: 2,
      state_name: "Kansas",
      seat: "KS-02",
      election_year: 2022,
      win_margin: 0.14,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/laturner-69302.png",
      act_blue_url: "https://secure.actblue.com/directory/KS/all/fed-house",
    },
    {
      name: "Tracey Mann",
      alignment: "Republican",
      type: "House",
      location: "Kan.",
      state_xx: "KS",
      seat_number: 1,
      state_name: "Kansas",
      seat: "KS-01",
      election_year: 2022,
      win_margin: 0.42,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/mann-20073168-17-h.png",
      act_blue_url: "https://secure.actblue.com/directory/KS/all/fed-house",
    },
    {
      name: "Roger Marshall",
      alignment: "Republican",
      type: "Senate",
      location: "Kan.",
      state_xx: "KS",
      seat_number: null,
      state_name: "Kansas",
      seat: null,
      election_year: 2026,
      win_margin: 0.11,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/marshall-65324-17-s.png",
      act_blue_url: "https://secure.actblue.com/directory/KS/all/fed-senate",
    },
    {
      name: "Harold Rogers",
      alignment: "Republican",
      type: "House",
      location: "Ky.",
      state_xx: "KY",
      seat_number: 5,
      state_name: "Kentucky",
      seat: "KY-05",
      election_year: 2022,
      win_margin: 0.68,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/rogers-208.png",
      act_blue_url: "https://secure.actblue.com/directory/KY/all/fed-house",
    },
    {
      name: "Garret Graves",
      alignment: "Republican",
      type: "House",
      location: "La.",
      state_xx: "LA",
      seat_number: 6,
      state_name: "Louisiana",
      seat: "LA-06",
      election_year: 2022,
      win_margin: 0.45,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/graves-64093.png",
      act_blue_url: "https://secure.actblue.com/directory/LA/all/fed-house",
    },
    {
      name: "Clay Higgins",
      alignment: "Republican",
      type: "House",
      location: "La.",
      state_xx: "LA",
      seat_number: 3,
      state_name: "Louisiana",
      seat: "LA-03",
      election_year: 2022,
      win_margin: 0.5,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/higgins-65612-19-h.png",
      act_blue_url: "https://secure.actblue.com/directory/LA/all/fed-house",
    },
    {
      name: "Mike Johnson",
      alignment: "Republican",
      type: "House",
      location: "La.",
      state_xx: "LA",
      seat_number: 4,
      state_name: "Louisiana",
      seat: "LA-04",
      election_year: 2022,
      win_margin: 0.35,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/johnson-4-19-h.png",
      act_blue_url: "https://secure.actblue.com/directory/LA/all/fed-house",
    },
    {
      name: "Steve Scalise",
      alignment: "Republican",
      type: "House",
      location: "La.",
      state_xx: "LA",
      seat_number: 1,
      state_name: "Louisiana",
      seat: "LA-01",
      election_year: 2022,
      win_margin: 0.47,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/scalise-54369-19-h.png",
      act_blue_url: "https://secure.actblue.com/directory/LA/all/fed-house",
    },
    {
      name: "John Kennedy",
      alignment: "Republican",
      type: "Senate",
      location: "La.",
      state_xx: "LA",
      seat_number: null,
      state_name: "Louisiana",
      seat: null,
      election_year: 2022,
      win_margin: 0.22,
      image:
        "https://www.nytimes.com/newsgraphics/2018/congress-headshots/cutouts/kennedy-la-sen.png",
      act_blue_url: "https://secure.actblue.com/directory/LA/all/fed-senate",
    },
    {
      name: "Andy Harris",
      alignment: "Republican",
      type: "House",
      location: "Md.",
      state_xx: "MD",
      seat_number: 1,
      state_name: "Maryland",
      seat: "MD-01",
      election_year: 2022,
      win_margin: 0.28,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/harris-58831-21-h.png",
      act_blue_url: "https://secure.actblue.com/directory/MD/all/fed-house",
    },
    {
      name: "Jack Bergman",
      alignment: "Republican",
      type: "House",
      location: "Mich.",
      state_xx: "MI",
      seat_number: 1,
      state_name: "Michigan",
      seat: "MI-01",
      election_year: 2022,
      win_margin: 0.25,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/bergman-65336-23-h.png",
      act_blue_url: "https://secure.actblue.com/directory/MI/all/fed-house",
    },
    {
      name: "Lisa McClain",
      alignment: "Republican",
      type: "House",
      location: "Mich.",
      state_xx: "MI",
      seat_number: 10,
      state_name: "Michigan",
      seat: "MI-10",
      election_year: 2022,
      win_margin: 0.32,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/mcclain-69093.png",
      act_blue_url: "https://secure.actblue.com/directory/MI/all/fed-house",
    },
    {
      name: "Tim Walberg",
      alignment: "Republican",
      type: "House",
      location: "Mich.",
      state_xx: "MI",
      seat_number: 7,
      state_name: "Michigan",
      seat: "MI-07",
      election_year: 2022,
      win_margin: 0.18,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/walberg-25659-23-h.png",
      act_blue_url: "https://secure.actblue.com/directory/MI/all/fed-house",
    },
    {
      name: "Michelle Fischbach",
      alignment: "Republican",
      type: "House",
      location: "Minn.",
      state_xx: "MN",
      seat_number: 7,
      state_name: "Minnesota",
      seat: "MN-07",
      election_year: 2022,
      win_margin: 0.13,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/fischbach-20073194-24-h.png",
      act_blue_url: "https://secure.actblue.com/directory/MN/all/fed-house",
    },
    {
      name: "Jim Hagedorn",
      alignment: "Republican",
      type: "House",
      location: "Minn.",
      state_xx: "MN",
      seat_number: 1,
      state_name: "Minnesota",
      seat: "MN-01",
      election_year: 2022,
      win_margin: 0.03,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/hagedorn-63961-24-h.png",
      act_blue_url: "https://secure.actblue.com/directory/MN/all/fed-house",
    },
    {
      name: "Michael Guest",
      alignment: "Republican",
      type: "House",
      location: "Miss.",
      state_xx: "MS",
      seat_number: 3,
      state_name: "Mississippi",
      seat: "MS-03",
      election_year: 2022,
      win_margin: 0.3,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/guest-20097-25-h.png",
      act_blue_url: "https://secure.actblue.com/directory/MS/all/fed-house",
    },
    {
      name: "Trent Kelly",
      alignment: "Republican",
      type: "House",
      location: "Miss.",
      state_xx: "MS",
      seat_number: 1,
      state_name: "Mississippi",
      seat: "MS-01",
      election_year: 2022,
      win_margin: 0.38,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/kelly-64498-25-h.png",
      act_blue_url: "https://secure.actblue.com/directory/MS/all/fed-house",
    },
    {
      name: "Steven Palazzo",
      alignment: "Republican",
      type: "House",
      location: "Miss.",
      state_xx: "MS",
      seat_number: 4,
      state_name: "Mississippi",
      seat: "MS-04",
      election_year: 2022,
      win_margin: 1,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/palazzo-60439-25-h.png",
      act_blue_url: "https://secure.actblue.com/directory/MS/all/fed-house",
    },
    {
      name: "Cindy Hyde-Smith",
      alignment: "Republican",
      type: "Senate",
      location: "Miss.",
      state_xx: "MS",
      seat_number: null,
      state_name: "Mississippi",
      seat: null,
      election_year: 2026,
      win_margin: 0.1,
      image:
        "https://www.nytimes.com/newsgraphics/2018/congress-headshots/cutouts/hyde-smith-ms-sen.png",
      act_blue_url: "https://secure.actblue.com/directory/MS/all/fed-senate",
    },
    {
      name: "Sam Graves",
      alignment: "Republican",
      type: "House",
      location: "Mo.",
      state_xx: "MO",
      seat_number: 6,
      state_name: "Missouri",
      seat: "MO-06",
      election_year: 2022,
      win_margin: 0.36,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/graves-1342-26-h.png",
      act_blue_url: "https://secure.actblue.com/directory/MO/all/fed-house",
    },
    {
      name: "Vicky Hartzler",
      alignment: "Republican",
      type: "House",
      location: "Mo.",
      state_xx: "MO",
      seat_number: 4,
      state_name: "Missouri",
      seat: "MO-04",
      election_year: 2022,
      win_margin: 0.38,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/hartzler-29019-26-h.png",
      act_blue_url: "https://secure.actblue.com/directory/MO/all/fed-house",
    },
    {
      name: "Billy Long",
      alignment: "Republican",
      type: "House",
      location: "Mo.",
      state_xx: "MO",
      seat_number: 7,
      state_name: "Missouri",
      seat: "MO-07",
      election_year: 2022,
      win_margin: 0.42,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/long-61089-26-h.png",
      act_blue_url: "https://secure.actblue.com/directory/MO/all/fed-house",
    },
    {
      name: "Blaine Luetkemeyer",
      alignment: "Republican",
      type: "House",
      location: "Mo.",
      state_xx: "MO",
      seat_number: 3,
      state_name: "Missouri",
      seat: "MO-03",
      election_year: 2022,
      win_margin: 0.4,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/luetkemeyer-55466-26-h.png",
      act_blue_url: "https://secure.actblue.com/directory/MO/all/fed-house",
    },
    {
      name: "Jason Smith",
      alignment: "Republican",
      type: "House",
      location: "Mo.",
      state_xx: "MO",
      seat_number: 8,
      state_name: "Missouri",
      seat: "MO-08",
      election_year: 2022,
      win_margin: 0.56,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/smith-62802-26-h.png",
      act_blue_url: "https://secure.actblue.com/directory/MO/all/fed-house",
    },
    {
      name: "Josh Hawley",
      alignment: "Republican",
      type: "Senate",
      location: "Mo.",
      state_xx: "MO",
      seat_number: null,
      state_name: "Missouri",
      seat: null,
      election_year: 2024,
      win_margin: 0.05,
      image:
        "https://www.nytimes.com/newsgraphics/2018/congress-headshots/cutouts/hawley-mo-sen.png",
      act_blue_url: "https://secure.actblue.com/directory/MO/all/fed-senate",
    },
    {
      name: "Matt Rosendale",
      alignment: "Republican",
      type: "House",
      location: "Mont.",
      state_xx: "MT",
      seat_number: 1,
      state_name: "Montana",
      seat: "MT-01",
      election_year: 2022,
      win_margin: 0.12,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/rosendale-19984-27-h.png",
      act_blue_url: "https://secure.actblue.com/directory/MT/all/fed-house",
    },
    {
      name: "Dan Bishop",
      alignment: "Republican",
      type: "House",
      location: "N.C.",
      state_xx: "NC",
      seat_number: 9,
      state_name: "North Carolina",
      seat: "NC-09",
      election_year: 2022,
      win_margin: 0.12,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/bishop-22311-34-h.png",
      act_blue_url: "https://secure.actblue.com/directory/NC/all/fed-house",
    },
    {
      name: "Ted Budd",
      alignment: "Republican",
      type: "House",
      location: "N.C.",
      state_xx: "NC",
      seat_number: 13,
      state_name: "North Carolina",
      seat: "NC-13",
      election_year: 2022,
      win_margin: 0.36,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/budd-64970-34-h.png",
      act_blue_url: "https://secure.actblue.com/directory/NC/all/fed-house",
    },
    {
      name: "Madison Cawthorn",
      alignment: "Republican",
      type: "House",
      location: "N.C.",
      state_xx: "NC",
      seat_number: 11,
      state_name: "North Carolina",
      seat: "NC-11",
      election_year: 2022,
      win_margin: 0.13,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/cawthorn-20073705-34-h.png",
      act_blue_url: "https://secure.actblue.com/directory/NC/all/fed-house",
    },
    {
      name: "Virginia Foxx",
      alignment: "Republican",
      type: "House",
      location: "N.C.",
      state_xx: "NC",
      seat_number: 5,
      state_name: "North Carolina",
      seat: "NC-05",
      election_year: 2022,
      win_margin: 0.36,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/foxx-1877-34-h.png",
      act_blue_url: "https://secure.actblue.com/directory/NC/all/fed-house",
    },
    {
      name: "Richard Hudson",
      alignment: "Republican",
      type: "House",
      location: "N.C.",
      state_xx: "NC",
      seat_number: 8,
      state_name: "North Carolina",
      seat: "NC-08",
      election_year: 2022,
      win_margin: 0.06,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/hudson-61758-34-h.png",
      act_blue_url: "https://secure.actblue.com/directory/NC/all/fed-house",
    },
    {
      name: "Gregory F. Murphy",
      alignment: "Republican",
      type: "House",
      location: "N.C.",
      state_xx: "NC",
      seat_number: 3,
      state_name: "North Carolina",
      seat: "NC-03",
      election_year: 2022,
      win_margin: 0.26,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/murphy-20072910-34-h.png",
      act_blue_url: "https://secure.actblue.com/directory/NC/all/fed-house",
    },
    {
      name: "David Rouzer",
      alignment: "Republican",
      type: "House",
      location: "N.C.",
      state_xx: "NC",
      seat_number: 7,
      state_name: "North Carolina",
      seat: "NC-07",
      election_year: 2022,
      win_margin: 0.2,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/rouzer-35605-34-h.png",
      act_blue_url: "https://secure.actblue.com/directory/NC/all/fed-house",
    },
    {
      name: "Jeff Van Drew",
      alignment: "Republican",
      type: "House",
      location: "N.J.",
      state_xx: "NJ",
      seat_number: 2,
      state_name: "New Jersey",
      seat: "NJ-02",
      election_year: 2022,
      win_margin: 0.06,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/van-drew-19998-31-h.png",
      act_blue_url: "https://secure.actblue.com/directory/NJ/all/fed-house",
    },
    {
      name: "Yvette Herrell",
      alignment: "Republican",
      type: "House",
      location: "N.M.",
      state_xx: "NM",
      seat_number: 2,
      state_name: "New Mexico",
      seat: "NM-02",
      election_year: 2022,
      win_margin: 0.08,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/herrell-20085-32-h.png",
      act_blue_url: "https://secure.actblue.com/directory/NM/all/fed-house",
    },
    {
      name: "Chris Jacobs",
      alignment: "Republican",
      type: "House",
      location: "N.Y.",
      state_xx: "NY",
      seat_number: 27,
      state_name: "New York",
      seat: "NY-27",
      election_year: 2022,
      win_margin: 0.21,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/jacobs-69033.png",
      act_blue_url: "https://secure.actblue.com/directory/NY/all/fed-house",
    },
    {
      name: "Nicole Malliotakis",
      alignment: "Republican",
      type: "House",
      location: "N.Y.",
      state_xx: "NY",
      seat_number: 11,
      state_name: "New York",
      seat: "NY-11",
      election_year: 2022,
      win_margin: 0.06,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/malliotakis-19220-33-h.png",
      act_blue_url: "https://secure.actblue.com/directory/NY/all/fed-house",
    },
    {
      name: "Elise M. Stefanik",
      alignment: "Republican",
      type: "House",
      location: "N.Y.",
      state_xx: "NY",
      seat_number: 21,
      state_name: "New York",
      seat: "NY-21",
      election_year: 2022,
      win_margin: 0.18,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/stefanik-63754-33-h.png",
      act_blue_url: "https://secure.actblue.com/directory/NY/all/fed-house",
    },
    {
      name: "Lee Zeldin",
      alignment: "Republican",
      type: "House",
      location: "N.Y.",
      state_xx: "NY",
      seat_number: 1,
      state_name: "New York",
      seat: "NY-01",
      election_year: 2022,
      win_margin: 0.1,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/zeldin-59740-33-h.png",
      act_blue_url: "https://secure.actblue.com/directory/NY/all/fed-house",
    },
    {
      name: "Adrian Smith",
      alignment: "Republican",
      type: "House",
      location: "Neb.",
      state_xx: "NB",
      seat_number: 3,
      state_name: "Nebraska",
      seat: "NB-03",
      election_year: 2022,
      win_margin: 0.61,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/smith-926-28-h.png",
      act_blue_url: "https://secure.actblue.com/directory/NB/all/fed-house",
    },
    {
      name: "Steve Chabot",
      alignment: "Republican",
      type: "House",
      location: "Ohio",
      state_xx: "OH",
      seat_number: 1,
      state_name: "Ohio",
      seat: "OH-01",
      election_year: 2022,
      win_margin: 0.07,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/chabot-1272-36-h.png",
      act_blue_url: "https://secure.actblue.com/directory/OH/all/fed-house",
    },
    {
      name: "Warren Davidson",
      alignment: "Republican",
      type: "House",
      location: "Ohio",
      state_xx: "OH",
      seat_number: 8,
      state_name: "Ohio",
      seat: "OH-08",
      election_year: 2022,
      win_margin: 0.38,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/davidson-64698.png",
      act_blue_url: "https://secure.actblue.com/directory/OH/all/fed-house",
    },
    {
      name: "Bob Gibbs",
      alignment: "Republican",
      type: "House",
      location: "Ohio",
      state_xx: "OH",
      seat_number: 7,
      state_name: "Ohio",
      seat: "OH-07",
      election_year: 2022,
      win_margin: 0.38,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/gibbs-57239-36-h.png",
      act_blue_url: "https://secure.actblue.com/directory/OH/all/fed-house",
    },
    {
      name: "Bill Johnson",
      alignment: "Republican",
      type: "House",
      location: "Ohio",
      state_xx: "OH",
      seat_number: 6,
      state_name: "Ohio",
      seat: "OH-06",
      election_year: 2022,
      win_margin: 0.48,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/johnson-60624-36-h.png",
      act_blue_url: "https://secure.actblue.com/directory/OH/all/fed-house",
    },
    {
      name: "Jim Jordan",
      alignment: "Republican",
      type: "House",
      location: "Ohio",
      state_xx: "OH",
      seat_number: 4,
      state_name: "Ohio",
      seat: "OH-04",
      election_year: 2022,
      win_margin: 0.39,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/jordan-57253-36-h.png",
      act_blue_url: "https://secure.actblue.com/directory/OH/all/fed-house",
    },
    {
      name: "Stephanie Bice",
      alignment: "Republican",
      type: "House",
      location: "Okla.",
      state_xx: "OK",
      seat_number: 5,
      state_name: "Oklahoma",
      seat: "OK-05",
      election_year: 2022,
      win_margin: 0.04,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/bice-20074039-37-h.png",
      act_blue_url: "https://secure.actblue.com/directory/OK/all/fed-house",
    },
    {
      name: "Tom Cole",
      alignment: "Republican",
      type: "House",
      location: "Okla.",
      state_xx: "OK",
      seat_number: 4,
      state_name: "Oklahoma",
      seat: "OK-04",
      election_year: 2022,
      win_margin: 0.39,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/cole-1398.png",
      act_blue_url: "https://secure.actblue.com/directory/OK/all/fed-house",
    },
    {
      name: "Kevin Hern",
      alignment: "Republican",
      type: "House",
      location: "Okla.",
      state_xx: "OK",
      seat_number: 1,
      state_name: "Oklahoma",
      seat: "OK-01",
      election_year: 2022,
      win_margin: 0.31,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/hern-20374-37-h.png",
      act_blue_url: "https://secure.actblue.com/directory/OK/all/fed-house",
    },
    {
      name: "Frank Lucas",
      alignment: "Republican",
      type: "House",
      location: "Okla.",
      state_xx: "OK",
      seat_number: 3,
      state_name: "Oklahoma",
      seat: "OK-03",
      election_year: 2022,
      win_margin: 0.56,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/lucas-1396-37-h.png",
      act_blue_url: "https://secure.actblue.com/directory/OK/all/fed-house",
    },
    {
      name: "Markwayne Mullin",
      alignment: "Republican",
      type: "House",
      location: "Okla.",
      state_xx: "OK",
      seat_number: 2,
      state_name: "Oklahoma",
      seat: "OK-02",
      election_year: 2022,
      win_margin: 0.53,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/mullin-62235-37-h.png",
      act_blue_url: "https://secure.actblue.com/directory/OK/all/fed-house",
    },
    {
      name: "Cliff Bentz",
      alignment: "Republican",
      type: "House",
      location: "Ore.",
      state_xx: "OR",
      seat_number: 2,
      state_name: "Oregon",
      seat: "OR-02",
      election_year: 2022,
      win_margin: 0.23,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/bentz-20073635-38-h.png",
      act_blue_url: "https://secure.actblue.com/directory/OR/all/fed-house",
    },
    {
      name: "John Joyce",
      alignment: "Republican",
      type: "House",
      location: "Pa.",
      state_xx: "PA",
      seat_number: 13,
      state_name: "Pennsylvania",
      seat: "PA-13",
      election_year: 2022,
      win_margin: 0.46,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/joyce-19966-39-h.png",
      act_blue_url: "https://secure.actblue.com/directory/PA/all/fed-house",
    },
    {
      name: "Fred Keller",
      alignment: "Republican",
      type: "House",
      location: "Pa.",
      state_xx: "PA",
      seat_number: 12,
      state_name: "Pennsylvania",
      seat: "PA-12",
      election_year: 2022,
      win_margin: 0.42,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/keller-22324-39-h.png",
      act_blue_url: "https://secure.actblue.com/directory/PA/all/fed-house",
    },
    {
      name: "Mike Kelly",
      alignment: "Republican",
      type: "House",
      location: "Pa.",
      state_xx: "PA",
      seat_number: 16,
      state_name: "Pennsylvania",
      seat: "PA-16",
      election_year: 2022,
      win_margin: 0.18,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/kelly-60917-39-h.png",
      act_blue_url: "https://secure.actblue.com/directory/PA/all/fed-house",
    },
    {
      name: "Daniel Meuser",
      alignment: "Republican",
      type: "House",
      location: "Pa.",
      state_xx: "PA",
      seat_number: 9,
      state_name: "Pennsylvania",
      seat: "PA-09",
      election_year: 2022,
      win_margin: 0.32,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/meuser-19952-39-h.png",
      act_blue_url: "https://secure.actblue.com/directory/PA/all/fed-house",
    },
    {
      name: "Scott Perry",
      alignment: "Republican",
      type: "House",
      location: "Pa.",
      state_xx: "PA",
      seat_number: 10,
      state_name: "Pennsylvania",
      seat: "PA-10",
      election_year: 2022,
      win_margin: 0.06,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/perry-61618-39-h.png",
      act_blue_url: "https://secure.actblue.com/directory/PA/all/fed-house",
    },
    {
      name: "Guy Reschenthaler",
      alignment: "Republican",
      type: "House",
      location: "Pa.",
      state_xx: "PA",
      seat_number: 14,
      state_name: "Pennsylvania",
      seat: "PA-14",
      election_year: 2022,
      win_margin: 0.3,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/reschenthaler-19975-39-h.png",
      act_blue_url: "https://secure.actblue.com/directory/PA/all/fed-house",
    },
    {
      name: "Lloyd Smucker",
      alignment: "Republican",
      type: "House",
      location: "Pa.",
      state_xx: "PA",
      seat_number: 11,
      state_name: "Pennsylvania",
      seat: "PA-11",
      election_year: 2022,
      win_margin: 0.26,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/smucker-64833-39-h.png",
      act_blue_url: "https://secure.actblue.com/directory/PA/all/fed-house",
    },
    {
      name: "Glenn Thompson",
      alignment: "Republican",
      type: "House",
      location: "Pa.",
      state_xx: "PA",
      seat_number: 15,
      state_name: "Pennsylvania",
      seat: "PA-15",
      election_year: 2022,
      win_margin: 0.46,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/thompson-58283-39-h.png",
      act_blue_url: "https://secure.actblue.com/directory/PA/all/fed-house",
    },
    {
      name: "Jeff Duncan",
      alignment: "Republican",
      type: "House",
      location: "S.C.",
      state_xx: "SC",
      seat_number: 3,
      state_name: "South Carolina",
      seat: "SC-03",
      election_year: 2022,
      win_margin: 0.42,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/duncan-57891-41-h.png",
      act_blue_url: "https://secure.actblue.com/directory/SC/all/fed-house",
    },
    {
      name: "Ralph Norman",
      alignment: "Republican",
      type: "House",
      location: "S.C.",
      state_xx: "SC",
      seat_number: 5,
      state_name: "South Carolina",
      seat: "SC-05",
      election_year: 2022,
      win_margin: 0.2,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/norman-51896-41-h.png",
      act_blue_url: "https://secure.actblue.com/directory/SC/all/fed-house",
    },
    {
      name: "Tom Rice",
      alignment: "Republican",
      type: "House",
      location: "S.C.",
      state_xx: "SC",
      seat_number: 7,
      state_name: "South Carolina",
      seat: "SC-07",
      election_year: 2022,
      win_margin: 0.24,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/rice-62109-41-h.png",
      act_blue_url: "https://secure.actblue.com/directory/SC/all/fed-house",
    },
    {
      name: "William Timmons",
      alignment: "Republican",
      type: "House",
      location: "S.C.",
      state_xx: "SC",
      seat_number: 4,
      state_name: "South Carolina",
      seat: "SC-04",
      election_year: 2022,
      win_margin: 0.25,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/timmons-20394-41-h.png",
      act_blue_url: "https://secure.actblue.com/directory/SC/all/fed-house",
    },
    {
      name: "Joe Wilson",
      alignment: "Republican",
      type: "House",
      location: "S.C.",
      state_xx: "SC",
      seat_number: 2,
      state_name: "South Carolina",
      seat: "SC-02",
      election_year: 2022,
      win_margin: 0.13,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/wilson-1410-41-h.png",
      act_blue_url: "https://secure.actblue.com/directory/SC/all/fed-house",
    },
    {
      name: "Tim Burchett",
      alignment: "Republican",
      type: "House",
      location: "Tenn.",
      state_xx: "TN",
      seat_number: 2,
      state_name: "Tennessee",
      seat: "TN-02",
      election_year: 2022,
      win_margin: 0.37,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/burchett-20787-43-h.png",
      act_blue_url: "https://secure.actblue.com/directory/TN/all/fed-house",
    },
    {
      name: "Scott DesJarlais",
      alignment: "Republican",
      type: "House",
      location: "Tenn.",
      state_xx: "TN",
      seat_number: 4,
      state_name: "Tennessee",
      seat: "TN-04",
      election_year: 2022,
      win_margin: 0.34,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/desjarlais-61091-43-h.png",
      act_blue_url: "https://secure.actblue.com/directory/TN/all/fed-house",
    },
    {
      name: "Chuck Fleischmann",
      alignment: "Republican",
      type: "House",
      location: "Tenn.",
      state_xx: "TN",
      seat_number: 3,
      state_name: "Tennessee",
      seat: "TN-03",
      election_year: 2022,
      win_margin: 0.37,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/fleischmann-60964-43-h.png",
      act_blue_url: "https://secure.actblue.com/directory/TN/all/fed-house",
    },
    {
      name: "Mark E. Green",
      alignment: "Republican",
      type: "House",
      location: "Tenn.",
      state_xx: "TN",
      seat_number: 7,
      state_name: "Tennessee",
      seat: "TN-07",
      election_year: 2022,
      win_margin: 0.43,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/green-1453-43-h.png",
      act_blue_url: "https://secure.actblue.com/directory/TN/all/fed-house",
    },
    {
      name: "Diana Harshbarger",
      alignment: "Republican",
      type: "House",
      location: "Tenn.",
      state_xx: "TN",
      seat_number: 1,
      state_name: "Tennessee",
      seat: "TN-01",
      election_year: 2022,
      win_margin: 0.53,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/harshbarger-20073935-43-h.png",
      act_blue_url: "https://secure.actblue.com/directory/TN/all/fed-house",
    },
    {
      name: "David Kustoff",
      alignment: "Republican",
      type: "House",
      location: "Tenn.",
      state_xx: "TN",
      seat_number: 8,
      state_name: "Tennessee",
      seat: "TN-08",
      election_year: 2022,
      win_margin: 0.39,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/kustoff-65268-43-h.png",
      act_blue_url: "https://secure.actblue.com/directory/TN/all/fed-house",
    },
    {
      name: "John Rose",
      alignment: "Republican",
      type: "House",
      location: "Tenn.",
      state_xx: "TN",
      seat_number: 6,
      state_name: "Tennessee",
      seat: "TN-06",
      election_year: 2022,
      win_margin: 0.5,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/rose-20411-43-h.png",
      act_blue_url: "https://secure.actblue.com/directory/TN/all/fed-house",
    },
    {
      name: "Jodey Arrington",
      alignment: "Republican",
      type: "House",
      location: "Texas",
      state_xx: "TX",
      seat_number: 19,
      state_name: "Texas",
      seat: "TX-19",
      election_year: 2022,
      win_margin: 0.52,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/arrington-64621-44-h.png",
      act_blue_url: "https://secure.actblue.com/directory/TX/all/fed-house",
    },
    {
      name: "Brian Babin",
      alignment: "Republican",
      type: "House",
      location: "Texas",
      state_xx: "TX",
      seat_number: 36,
      state_name: "Texas",
      seat: "TX-36",
      election_year: 2022,
      win_margin: 0.5,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/babin-70006-44-h.png",
      act_blue_url: "https://secure.actblue.com/directory/TX/all/fed-house",
    },
    {
      name: "Michael C. Burgess",
      alignment: "Republican",
      type: "House",
      location: "Texas",
      state_xx: "TX",
      seat_number: 26,
      state_name: "Texas",
      seat: "TX-26",
      election_year: 2022,
      win_margin: 0.24,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/burgess-1017-44-h.png",
      act_blue_url: "https://secure.actblue.com/directory/TX/all/fed-house",
    },
    {
      name: "John R. Carter",
      alignment: "Republican",
      type: "House",
      location: "Texas",
      state_xx: "TX",
      seat_number: 31,
      state_name: "Texas",
      seat: "TX-31",
      election_year: 2022,
      win_margin: 0.09,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/carter-1441.png",
      act_blue_url: "https://secure.actblue.com/directory/TX/all/fed-house",
    },
    {
      name: "Michael Cloud",
      alignment: "Republican",
      type: "House",
      location: "Texas",
      state_xx: "TX",
      seat_number: 27,
      state_name: "Texas",
      seat: "TX-27",
      election_year: 2022,
      win_margin: 0.28,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/cloud-801-44-h.png",
      act_blue_url: "https://secure.actblue.com/directory/TX/all/fed-house",
    },
    {
      name: "Pat Fallon",
      alignment: "Republican",
      type: "House",
      location: "Texas",
      state_xx: "TX",
      seat_number: 4,
      state_name: "Texas",
      seat: "TX-04",
      election_year: 2022,
      win_margin: 0.53,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/fallon-20073300-44-h.png",
      act_blue_url: "https://secure.actblue.com/directory/TX/all/fed-house",
    },
    {
      name: "Louie Gohmert",
      alignment: "Republican",
      type: "House",
      location: "Texas",
      state_xx: "TX",
      seat_number: 1,
      state_name: "Texas",
      seat: "TX-01",
      election_year: 2022,
      win_margin: 0.46,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/gohmert-1883-44-h.png",
      act_blue_url: "https://secure.actblue.com/directory/TX/all/fed-house",
    },
    {
      name: "Lance Gooden",
      alignment: "Republican",
      type: "House",
      location: "Texas",
      state_xx: "TX",
      seat_number: 5,
      state_name: "Texas",
      seat: "TX-05",
      election_year: 2022,
      win_margin: 0.26,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/gooden-19491-44-h.png",
      act_blue_url: "https://secure.actblue.com/directory/TX/all/fed-house",
    },
    {
      name: "Ronny Jackson",
      alignment: "Republican",
      type: "House",
      location: "Texas",
      state_xx: "TX",
      seat_number: 13,
      state_name: "Texas",
      seat: "TX-13",
      election_year: 2022,
      win_margin: 0.61,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/jackson-68255.png",
      act_blue_url: "https://secure.actblue.com/directory/TX/all/fed-house",
    },
    {
      name: "Troy Nehls",
      alignment: "Republican",
      type: "House",
      location: "Texas",
      state_xx: "TX",
      seat_number: 22,
      state_name: "Texas",
      seat: "TX-22",
      election_year: 2022,
      win_margin: 0.07,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/nehls-20073581-44-h.png",
      act_blue_url: "https://secure.actblue.com/directory/TX/all/fed-house",
    },
    {
      name: "August Pfluger",
      alignment: "Republican",
      type: "House",
      location: "Texas",
      state_xx: "TX",
      seat_number: 11,
      state_name: "Texas",
      seat: "TX-11",
      election_year: 2022,
      win_margin: 0.62,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/pfluger-68246.png",
      act_blue_url: "https://secure.actblue.com/directory/TX/all/fed-house",
    },
    {
      name: "Pete Sessions",
      alignment: "Republican",
      type: "House",
      location: "Texas",
      state_xx: "TX",
      seat_number: 17,
      state_name: "Texas",
      seat: "TX-17",
      election_year: 2022,
      win_margin: 0.15,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/sessions-358-44-h.png",
      act_blue_url: "https://secure.actblue.com/directory/TX/all/fed-house",
    },
    {
      name: "Beth Van Duyne",
      alignment: "Republican",
      type: "House",
      location: "Texas",
      state_xx: "TX",
      seat_number: 24,
      state_name: "Texas",
      seat: "TX-24",
      election_year: 2022,
      win_margin: 0.02,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/van-duyne-20073274-44-h.png",
      act_blue_url: "https://secure.actblue.com/directory/TX/all/fed-house",
    },
    {
      name: "Randy Weber",
      alignment: "Republican",
      type: "House",
      location: "Texas",
      state_xx: "TX",
      seat_number: 14,
      state_name: "Texas",
      seat: "TX-14",
      election_year: 2022,
      win_margin: 0.24,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/weber-61980-44-h.png",
      act_blue_url: "https://secure.actblue.com/directory/TX/all/fed-house",
    },
    {
      name: "Roger Williams",
      alignment: "Republican",
      type: "House",
      location: "Texas",
      state_xx: "TX",
      seat_number: 25,
      state_name: "Texas",
      seat: "TX-25",
      election_year: 2022,
      win_margin: 0.14,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/williams-62001-44-h.png",
      act_blue_url: "https://secure.actblue.com/directory/TX/all/fed-house",
    },
    {
      name: "Ron Wright",
      alignment: "Republican",
      type: "House",
      location: "Texas",
      state_xx: "TX",
      seat_number: 6,
      state_name: "Texas",
      seat: "TX-06",
      election_year: 2022,
      win_margin: 0.09,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/wright-19504-44-h.png",
      act_blue_url: "https://secure.actblue.com/directory/TX/all/fed-house",
    },
    {
      name: "Ted Cruz",
      alignment: "Republican",
      type: "Senate",
      location: "Texas",
      state_xx: "TX",
      seat_number: null,
      state_name: "Texas",
      seat: null,
      election_year: 2024,
      win_margin: 0.13,
      image:
        "https://www.nytimes.com/newsgraphics/2018/congress-headshots/cutouts/cruz-tx-sen.png",
      act_blue_url: "https://secure.actblue.com/directory/TX/all/fed-senate",
    },
    {
      name: "Burgess Owens",
      alignment: "Republican",
      type: "House",
      location: "Utah",
      state_xx: "UT",
      seat_number: 4,
      state_name: "Utah",
      seat: "UT-04",
      election_year: 2022,
      win_margin: 0.01,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/owens-20073826-45-h.png",
      act_blue_url: "https://secure.actblue.com/directory/UT/all/fed-house",
    },
    {
      name: "Chris Stewart",
      alignment: "Republican",
      type: "House",
      location: "Utah",
      state_xx: "UT",
      seat_number: 2,
      state_name: "Utah",
      seat: "UT-02",
      election_year: 2022,
      win_margin: 0.22,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/stewart-61890-45-h.png",
      act_blue_url: "https://secure.actblue.com/directory/UT/all/fed-house",
    },
    {
      name: "Ben Cline",
      alignment: "Republican",
      type: "House",
      location: "Va.",
      state_xx: "VA",
      seat_number: 6,
      state_name: "Virginia",
      seat: "VA-06",
      election_year: 2022,
      win_margin: 0.3,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/cline-20447-47-h.png",
      act_blue_url: "https://secure.actblue.com/directory/VA/all/fed-house",
    },
    {
      name: "Bob Good",
      alignment: "Republican",
      type: "House",
      location: "Va.",
      state_xx: "VA",
      seat_number: 5,
      state_name: "Virginia",
      seat: "VA-05",
      election_year: 2022,
      win_margin: 0.06,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/good-20073701-47-h.png",
      act_blue_url: "https://secure.actblue.com/directory/VA/all/fed-house",
    },
    {
      name: "Morgan Griffith",
      alignment: "Republican",
      type: "House",
      location: "Va.",
      state_xx: "VA",
      seat_number: 9,
      state_name: "Virginia",
      seat: "VA-09",
      election_year: 2022,
      win_margin: 1,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/griffith-58574-47-h.png",
      act_blue_url: "https://secure.actblue.com/directory/VA/all/fed-house",
    },
    {
      name: "Robert J. Wittman",
      alignment: "Republican",
      type: "House",
      location: "Va.",
      state_xx: "VA",
      seat_number: 1,
      state_name: "Virginia",
      seat: "VA-01",
      election_year: 2022,
      win_margin: 0.16,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/wittman-57798-47-h.png",
      act_blue_url: "https://secure.actblue.com/directory/VA/all/fed-house",
    },
    {
      name: "Carol Miller",
      alignment: "Republican",
      type: "House",
      location: "W.Va.",
      state_xx: "WV",
      seat_number: 3,
      state_name: "West Virginia",
      seat: "WV-03",
      election_year: 2022,
      win_margin: 0.42,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/miller-70004-49-h.png",
      act_blue_url: "https://secure.actblue.com/directory/WV/all/fed-house",
    },
    {
      name: "Alexander X. Mooney",
      alignment: "Republican",
      type: "House",
      location: "W.Va.",
      state_xx: "WV",
      seat_number: 2,
      state_name: "West Virginia",
      seat: "WV-02",
      election_year: 2022,
      win_margin: 0.26,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/mooney-22596-49-h.png",
      act_blue_url: "https://secure.actblue.com/directory/WV/all/fed-house",
    },
    {
      name: "Scott Fitzgerald",
      alignment: "Republican",
      type: "House",
      location: "Wis.",
      state_xx: "WI",
      seat_number: 5,
      state_name: "Wisconsin",
      seat: "WI-05",
      election_year: 2022,
      win_margin: 0.2,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/fitzgerald-20073862-50-h.png",
      act_blue_url: "https://secure.actblue.com/directory/WI/all/fed-house",
    },
    {
      name: "Tom Tiffany",
      alignment: "Republican",
      type: "House",
      location: "Wis.",
      state_xx: "WI",
      seat_number: 7,
      state_name: "Wisconsin",
      seat: "WI-07",
      election_year: 2022,
      win_margin: 0.22,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/tiffany-20073295-50-h.png",
      act_blue_url: "https://secure.actblue.com/directory/WI/all/fed-house",
    },
    {
      name: "Cynthia Lummis",
      alignment: "Republican",
      type: "Senate",
      location: "Wyo.",
      state_xx: "WY",
      seat_number: null,
      state_name: "Wyoming",
      seat: null,
      election_year: 2026,
      win_margin: 0.46,
      image:
        "https://static01.nyt.com/elections-assets/2020/assets/images/candidates/lummis-49396.png",
      act_blue_url: "https://secure.actblue.com/directory/WY/all/fed-senate",
    },
  ];
}
